### PR TITLE
Damien

### PR DESCRIPTION
**Pull request by bahati365**
-test for ReadingGeneratorController, LoginController and CardLookUpController completed.
-They should run perfectly fine without errors

### CODE REVIEW

**Review by shaunamia — CHANGES_REQUESTED** [review]
These tests do not test anything meaningfully. When calling assertEquals, you are essentially checking if the expected value is equal to the actual value, but in these tests, you are storing the same method call in the expected and the actual value, so the test will always pass, even if the method does not behave how it should.

**Comment by bahati365** [comment]
> These tests do not test anything meaningfully. When calling assertEquals, you are essentially checking if the expected value is equal to the actual value, but in these tests, you are storing the same method call in the expected and the actual value, so the test will always pass, even if the method does not behave how it should.

What do you mean? Isn't how the methods is supposed to behave? I tested the methods based on how they are called in the controllers. also there are other classes which take care of most of the cases. here we are testing if the controllers behave the way we want them to behave based on how they are being implemented. for instance if it says in the method that it always returns true then that is what is being tested. you can try running the tests and see. Thanks

**Review by murtiturti — APPROVED** [review]
I am not sure what these tests are testing, but ok.

**Comment by bahati365** [comment]
> I am not sure what these tests are testing, but ok.

hahaha, thats kinda funny man

**Pull request merged**
